spring:
  profiles: dev, uat, prd
  datasource:
    url: jdbc:h2:mem:notMemDb
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
