spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: test
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
